# config/packages/doctrine.yaml

doctrine:
  dbal:
    driver: 'pdo_mysql'
    server_version: '%env(DATABASE_VERSION)%'
    url: '%env(DATABASE_URL)%'
    charset: 'utf8'
    default_table_options:
      charset: 'utf8'
      collate: 'utf8_unicode_ci'
      engine: 'InnoDB'
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    default_entity_manager: default
    metadata_cache_driver: array
    query_cache_driver: array
    result_cache_driver: array
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: 'annotation'
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: 'App'
    dql:
      numeric_functions:
        day: App\DQL\DayFunction
        month: App\DQL\MonthFunction
        year: App\DQL\YearFunction
        weekday: App\DQL\WeekdayFunction
      string_functions:
        date_format: App\DQL\DateFormatFunction
        replace: App\DQL\ReplaceFunction
