doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
#    host: '%database_host%'
#    port: '%database_port%'
#    dbname: '%database_name%'
#    user: '%database_user%'
#    password: '%database_password%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App


        metadata_cache_driver: array
        query_cache_driver: array
        result_cache_driver: array
        dql:
            numeric_functions:
                day: AppBundle\DQL\DayFunction
        	month: AppBundle\DQL\MonthFunction
        	year: AppBundle\DQL\YearFunction
        	weekday: AppBundle\DQL\WeekdayFunction
      	    string_functions:
        	date_format: AppBundle\DQL\DateFormatFunction
        	replace: AppBundle\DQL\ReplaceFunction




