# config/packages/framework.yaml

framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: true
  ide: ~
  disallow_search_engine_index: false
  trusted_hosts: ~
  form:
    enabled: true
  csrf_protection:
    enabled: true
  esi: false
  fragments: false
  #http_client: ~
  request: ~
  session:
    enabled: true
    cookie_secure: 'auto'
    cookie_samesite: 'lax'
    cookie_httponly: true
    handler_id: 'session.handler.native_file'
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
  assets: ~
  property_access: ~
  property_info:
    enabled: false
  annotations: ~
  serializer: ~
  php_errors:
    log: true
