framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
   	handler_id: session.handler.native_file
    	save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    fragments: ~
    php_errors:
        log: true
  ide: ~
  trusted_hosts: ~
  form:
    enabled: true
  assets: ~
  templating:
    engines: 'twig'
  property_access: ~
  annotations: ~
  serializer: ~


