# config/packages/framework.yaml

framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: true
  ide: ~
  disallow_search_engine_index: false
  trusted_hosts: ~
  form:
    enabled: true
  csrf_protection:
    enabled: true
  esi: false
  fragments: ~
  http_client: ~
  request: ~
  session:
    handler_id: 'session.handler.native_file'
    cookie_secure: 'auto'
    cookie_samesite: 'strict'
    cookie_httponly: true
    enabled: true
  assets: ~
  property_access: ~
  property_info:
    enabled: false
  annotations: ~
  serializer: ~
  php_errors:
    log: true
  cache: ~
