# config/packages/security.yaml

security:
  encoders:
    App\Entity\Utente:
      algorithm: 'auto'
  providers:
    db_provider:
      entity:
        class: 'App:Utente'
        property: 'username'
  firewalls:
    main:
      provider: 'db_provider'
      anonymous: lazy
      switch_user:
        role: 'ROLE_AMMINISTRATORE'
        parameter: '_alias'
      logout:
        path: '/logout/'
        target: '/login/form/'
        invalidate_session: true
        handlers: ['App\Security\LogoutHandler']
      guard:
        authenticators:
          - 'App\Security\GSuiteAuthenticator'
          - 'App\Security\FormAuthenticator'
          - 'App\Security\AppAuthenticator'
          - 'App\Security\TokenAuthenticator'
          - 'App\Security\EnrollAuthenticator'
        entry_point: 'App\Security\GSuiteAuthenticator'
