# config/packages/translation.yaml

framework:
  default_locale: '%locale%'
  enabled_locales: ['%locale%']
  translator:
    enabled: true
    fallbacks: '%locale%'
    default_path: '%kernel.project_dir%/PERSONAL/translations'
    paths:
      - '%kernel.project_dir%/translations'
