# config/packages/twig.yaml

twig:
  date:
    format: '%locale_date%'
  number_format:
    decimals: 2
    decimal_point: ','
    thousands_separator: ''
  form_themes: ['form.html.twig']
  strict_variables: '%kernel.debug%'
  exception_controller: null
  paths:
    'PERSONAL/templates': ~
    'PERSONAL/data': 'data'
