# config/packages/twig.yaml

twig:
  globals:
    LOCAL_PATH: '%env(LOCAL_PATH)%'
  date:
    format: '%locale_date%'
  number_format:
    decimals: 2
    decimal_point: ','
    thousands_separator: ''
  debug: '%kernel.debug%'
  form_themes: ['form.html.twig']
  strict_variables: '%kernel.debug%'
  default_path: '%kernel.project_dir%/templates'
  exception_controller: null

