# app/config/config_prod.yml

### importa configurazioni
imports:
  - { resource: config.yml }

### configurazione FrameworkBundle
framework:
  test: false
  profiler:
    enabled: false
  router:
    resource: '%kernel.project_dir%/app/config/routing.yml'
    strict_requirements: ~

### configurazione monolog
monolog:
  use_microseconds: false
  channels: ["command"]
  handlers:
    main:
      type: rotating_file
      max_files: 30
      path: "%kernel.logs_dir%/app_%kernel.environment%.log"
      level: warning
      channels: ["!command"]
    command:
      type: rotating_file
      max_files: 30
      path: "%kernel.logs_dir%/command_%kernel.environment%.log"
      level: warning
      channels: ["command"]
