# app/config/config_test.yml

### importa configurazioni
imports:
  - { resource: config.yml }

### configurazione framework
framework:
  test: true
  profiler:
    enabled: true
    collect: false
  router:
    resource: '%kernel.project_dir%/app/config/routing_dev.yml'
    strict_requirements: true
  session:
    storage_id: session.storage.mock_file

### configurazione swiftmailer
#swiftmailer:
#  delivery_address: test-email

### configurazione webprofiler
web_profiler:
  toolbar: false
  intercept_redirects: false

### configurazione monolog
monolog:
  use_microseconds: false
  channels: ["command"]
  handlers:
    main:
      type: rotating_file
      max_files: 10
      path: "%kernel.logs_dir%/app_%kernel.environment%.log"
      level: debug
      channels: ["!command"]
    command:
      type: rotating_file
      max_files: 10
      path: "%kernel.logs_dir%/command_%kernel.environment%.log"
      level: debug
      channels: ["command"]
    console:
      type: console
