# app/config/parameters.yml

### DEFINIZIONE PARAMETRI
parameters:
  database_host:          127.0.0.1
  database_port:          ~
  database_name:          giuaschool
  database_user:          root
  database_password:      ~
  mailer_transport:       smtp
  mailer_host:            127.0.0.1
  mailer_user:            ~
  mailer_password:        ~

  # A secret key that's used to generate certain security-related tokens
  secret:                 ThisTokenIsNotSoSecretChangeIt

  # path to special dirs
  dir_scrutini:   '%kernel.project_dir%/FILES/archivio/scrutini'
  dir_registri:   '%kernel.project_dir%/FILES/archivio/registri'
  dir_classi:     '%kernel.project_dir%/FILES/archivio/classi'
  dir_avvisi:     '%kernel.project_dir%/FILES/upload/avvisi'
  dir_circolari:  '%kernel.project_dir%/FILES/upload/circolari'
  dir_foto:       '%kernel.project_dir%/FILES/upload/foto'
  dir_tmp:        '%kernel.project_dir%/FILES/upload/tmp'
