version: '3.8'

services:

  mariadb:
    image: mariadb:10.3
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "root"

  php-apache:
    build:
      context: ./php-apache
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
    links:
      - 'mariadb'

volumes:
    mariadb:
