# config/packages/prod/monolog.yaml

monolog:
  use_microseconds: false
  channels: ['command']
  handlers:
    main:
      type: rotating_file
      max_files: 30
      path: '%kernel.logs_dir%/app_%kernel.environment%.log'
      level: warning
      channels: ['!command', '!console']
    command:
      type: rotating_file
      max_files: 30
      path: '%kernel.logs_dir%/command_%kernel.environment%.log'
      level: notice
      channels: ['command', 'console']
