# config/packages/prod/monolog.yaml

monolog:
  use_microseconds: false
  channels:
    - command
    - messenger_logger
  handlers:
    main:
      type: rotating_file
      max_files: 30
      path: '%kernel.logs_dir%/app_%kernel.environment%.log'
      level: '%env(LOG_LEVEL)%'
      channels: ['!command', '!console']
    command:
      type: rotating_file
      max_files: 30
      path: '%kernel.logs_dir%/command_%kernel.environment%.log'
      level: notice
      channels: ['command', 'console']
    messenger:
      type: rotating_file
      max_files: 10
      path: '%kernel.logs_dir%/messenger_%kernel.environment%.log'
      level: debug
      channels: ['messenger_logger']
