name: Tests

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Build image
        run: docker build -t giuaschool:test -f docker/DockerfileTest .
        
