name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

 #     - name: Push to GitHub Packages
 #       uses: docker/build-push-action@v1
 #       with:
 #         dockerfile: ./docker/Dockerfile
 #         username: ${{ github.actor }}
 #         password: ${{ secrets.GITHUB_TOKEN }}
 #         registry: docker.pkg.github.com
 #         repository: trinko/giuaschool/giuaschool-test
 #         tag_with_ref: true

#      - name: Login
#        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
#      - name: Build 
#        run: docker build -t docker.pkg.github.com/trinko/giuaschool/giuaschool-test .
#      - name: Push 
#        run: docker push docker.pkg.github.com/trinko/giuaschool/giuaschool-test
 
 
      - name: publish
        uses: pennsignals/publish_docker-compose@v0.1.0
        with:
          docker_compose: ./docker/docker-compose.yml
          repo_token: "${{ secrets.GITHUB_TOKEN }}"

