name: Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Build & push image on DockerHub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: trinkodok/giuaschool
          registry: docker.io
          dockerfile: ./docker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build & push image on GitHub
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: giuaschool/giuaschool
          registry: docker.pkg.github.com
          dockerfile: ./docker/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
