name: Build Application

on:
  #-- push:
    #-- branches: [ master ]
  #release:
  #  types: [published]
  workflow_dispatch:
  #  inputs:
  #    tags:
  #      description: 'Tag list'
  #      required: true
  #      default: 'latest'

jobs:

  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        id: build-image
        run: docker build -t giuaschool:latest -f docker/Dockerfile .
        
      - name: Push to GitHub
        uses: redhat-actions/push-to-registry@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          image: giuaschool
          tags: latest

      - name: Push to DockerHub
        uses: redhat-actions/push-to-registry@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          image: trinkodok/giuaschool
          tags: latest
