name: Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Prepare
        id: prep
        run: |
          DHUB_IMAGE=trinkodok/giuaschool
          GHUB_IMAGE=docker.pkg.github.com/trinko/giuaschool
          VERSION=${GITHUB_REF#refs/tags/}
          TAGS="${DHUB_IMAGE}:${VERSION},${DHUB_IMAGE}:latest"
          TAGS="${TAGS},${GH_IMAGE}:${VERSION},${GH_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=dhub_image::${DHUB_IMAGE}
          echo ::set-output name=ghub_image::${GHUB_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Package
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          labels: org.opencontainers.image.version=${{ steps.prep.outputs.version }}
      
      #- name: Push to Docker Hub
      #  uses: docker/build-push-action@v1
      #  with:
      #    dockerfile: ./docker/Dockerfile
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      #    repository: trinkodok/giuaschool
      #    tag_with_ref: true
                       
      #- name: Push to GitHub Packages
      #  #id: docker_build
      #  uses: docker/build-push-action@v1
      #  with: 
      #    dockerfile: ./docker/Dockerfile
          #tags: trinko/giuaschool:latest 
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
      #    registry: docker.pkg.github.com
      #    repository: trinko/giuaschool/giuaschool-test
      #    tag_with_ref: true

      #- name: Image digest
      #  run: echo ${{ steps.docker_build.outputs.digest }}
        
