name: Build

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build and create a build code
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: tests/docker/Dockerfile
          push: true
          tags: |
            trinkodok/giuaschool:latest
            ghcr.io/trinko/giuaschool:latest

      - name: Archive build code
        run: |
          docker run --name "gs_release" ghcr.io/trinko/giuaschool:latest tests/docker/entrypoint-release.sh
          mkdir builds
          docker cp gs_release:/var/www/giuaschool/giuaschool-release.zip builds/giuaschool-build-latest.zip

      - name: Upload latest build
        uses: EndBug/add-and-commit@v7
        with:
          add: builds/giuaschool-build-latest.zip --force
          branch: builds
          branch_mode: create
          push: '--force --set-upstream origin builds'
          pull: 'NO-PULL'
          default_author: github_actor
          message: 'Upload latest build'

      - name: Generate changelog from latest release
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog page
        run: |
          mkdir docs
          echo "---" > docs/latest-build.md
          echo "layout: default" >> docs/latest-build.md
          echo "title: Ultima modifica" >> docs/latest-build.md
          echo "nav_order: 11" >> docs/latest-build.md
          echo "---" >> docs/latest-build.md
          echo "" >> docs/latest-build.md
          echo "# Ultima modifica"  >> docs/latest-build.md
          echo "{: .text-center .fw-400 .pb-5}" >> docs/latest-build.md
          echo "" >> docs/latest-build.md
          echo "Data e ora dell'ultima modifica: `TZ='Europe/Rome' date +'%d/%m/%Y %H:%M'`" >> docs/latest-build.md
          echo "" >> docs/latest-build.md
          echo "Lista delle modifiche effettuate dopo il rilascio della Versione {{ site.data.version.tag }}:"  >> docs/latest-build.md
          echo "" >> docs/latest-build.md
          echo "${{ steps.changelog.outputs.changelog }}"  >> docs/latest-build.md

      - name: Add changelog page to documentation
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'docs/latest-build.md'
          destination_repo: 'trinko/giuaschool-docs'
          destination_branch: 'master'
          user_name: ${{ github.actor }}
          user_email: '${{ github.actor }}@users.noreply.github.com'
          commit_message: 'Add changelog page to documentation'
