name: Build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      #- name: Login
      #  uses: docker/login-action@v1
      #  with:
      #    registry: docker.pkg.github.com
      #    username: ${{ github.actor }}
      #    password: ${{ secrets.GITHUB_TOKEN }}
             
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: trinkodok/giuaschool
          tag_with_ref: true
                       
      - name: Push to GitHub Packages
        #id: docker_build
        uses: docker/build-push-action@v1
        with: 
          dockerfile: ./docker/Dockerfile
          #tags: trinko/giuaschool:latest 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: trinko/giuaschool/giuaschool-test
          tag_with_ref: true

      #- name: Image digest
      #  run: echo ${{ steps.docker_build.outputs.digest }}
        
