name: Codacy coverage reporter

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]
  workflow_dispatch:
    
jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: test
        run: ls -la
        shell: sh
       
      #- uses: actions/checkout@master
      #- name: Run codacy-coverage-reporter
      #  uses: codacy/codacy-coverage-reporter-action@master
      #  with:
      #    project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #    coverage-reports: clover.xml
          
