name: Test

on:
  push:
    branches: [ master ]

jobs:

  prova:
    name: Cambio spazio swap
    runs-on: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
