name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      prerelease:
        description: 'Set TRUE for pre-release'
        required: false
        default: 'FALSE'

jobs:

  release:
    name: Publish a new release
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Generate changelog from latest release
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          release_name: "Versione ${{ github.event.inputs.version }}"
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease == 'TRUE' }}

      - name: Archive release code
        run: |
          docker run --name "gs_release" ghcr.io/trinko/giuaschool:latest tests/docker/entrypoint-release.sh
          mkdir builds
          docker cp gs_release:/var/www/giuaschool/giuaschool-release.zip builds/giuaschool-release-latest.zip

      - name: Publish latest release code
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: builds/giuaschool-release-latest.zip
          asset_name: giuaschool-release-latest.zip
          tag: "v${{ github.event.inputs.version }}"

      - name: Generate changelog pages
        run: |
          mkdir docs
          #####----- latest release page
          echo "---" > docs/latest-release.md
          echo "layout: default" >> docs/latest-release.md
          echo "title: 'Ultima versione'" >> docs/latest-build.md
          echo "nav_order: 90" >> docs/latest-release.md
          echo "---" >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "# Ultima versione"  >> docs/latest-release.md
          echo "{: .text-center .fw-400}" >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "Versione: {{ site.data.version.tag }}" >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "Data e ora di rilascio: `TZ='Europe/Rome' date +'%x %X'`" >> docs/latest-build.md
          echo "" >> docs/latest-release.md
          echo "Lista delle modifiche incluse nella nuova versione:"  >> docs/latest-release.md
          echo "" >> docs/latest-release.md
          echo "${{ steps.changelog.outputs.changelog }}"  >> docs/latest-release.md
          #####----- latest build page
          echo "---" > docs/latest-build.md
          echo "layout: default" >> docs/latest-build.md
          echo "title: 'Ultima modifica'" >> docs/latest-build.md
          echo "nav_order: 91" >> docs/latest-build.md
          echo "---" >> docs/latest-build.md
          echo "" >> docs/latest-build.md
          echo "# Ultima modifica"  >> docs/latest-build.md
          echo "{: .text-center .fw-400}" >> docs/latest-build.md
          echo "" >> docs/latest-build.md
          echo "Nessuna modifica dal rilascio dell'ultima versione" >> docs/latest-build.md
          #####----- data
          echo "tag: ${{ github.event.inputs.version }}" > docs/version.yml

      - name: Add version tag to documentation
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: docs/version.yml
          dst_path: /_data/version.yml
          dst_owner: trinko
          dst_repo_name: giuaschool-docs
          commit_message: 'Create version tag'

      - name: Add changelog pages to documentation
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: docs/
          file_filter: *.md
          dst_path: /
          dst_owner: trinko
          dst_repo_name: giuaschool-docs
          commit_message: 'Create gh-pages for changelog'
