name: Test Pull Request

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:

  test:
    name: Build test environment and run tests
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Run tests
        run: |
          docker run --name "gs_test" --add-host=giuaschool_test:127.0.0.1 --add-host=chrome_headless:127.0.0.1 . tests/docker/entrypoint-test.sh
