name: Test2

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        run: |
          docker build -t "gs:prod" -f tests/docker/Dockerfile .
          docker save --output docker-prod-${{ github.event.name }}.tar gs:prod

      - name: Upload docker image for PROD environment
        uses: actions/upload-artifact@v3
        with:
          name: docker-prod
          path: docker-prod-${{ github.event.name }}.tar
          retention-days: 1

