name: Test

on:
  workflow_dispatch:
  #-- push:
    #-- branches: [ master ]
  #-- pull_request:
    #-- types: [opened, reopened, synchronize]

jobs:

  build:
    name: Build images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        run: |
          docker build -t "gs:prod" -f tests/docker/Dockerfile .
          docker build -t "gs:dev" -f tests/docker/DockerfileDev .
          docker build -t "gs:test" -f tests/docker/DockerfileTest .
          docker save --output docker-test-${{ github.event_name }}.tar gs:test

      - name: Upload docker image for TEST environment
        uses: actions/upload-artifact@v3
        with:
          name: docker-test-${{ github.event_name }}
          path: docker-test-${{ github.event_name }}.tar
          retention-days: 1

  test-phpunit:
    name: PhpUnit tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:

      - name: Download docker image
        uses: actions/download-artifact@v3
        with:
          name: docker-test-${{ github.event_name }}

      - name: Load docker image
        run: docker load --input docker-test-${{ github.event_name }}.tar

      - name: Run phpunit
        run: docker run --add-host=giuaschool_test:127.0.0.1 --add-host=chrome_headless:127.0.0.1 gs:test tests/docker/test-phpunit.sh

      - name: Codacy coverage report
        if: ${{ github.event.event_name == 'push' }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml

  test-behat:
    name: Behat tests
    needs: build
    runs-on: ubuntu-latest
    env:
      FEATURE: ${{ matrix.feature }}
    strategy:
      matrix:
        feature:
          - '_CertificatoStaff'
          - 'documenti_alunni'
          - 'documenti_bacheca'
          - 'documenti_bes'
          - 'documenti_docenti'
          - 'documenti_download'
          - 'documenti_maggio'
          - 'documenti_piani'
          - 'documenti_programmi'
          - 'documenti_relazioni'

    steps:

      - name: Set swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Run behat
        run: docker run --add-host=giuaschool_test:127.0.0.1 --add-host=chrome_headless:127.0.0.1 gs:build tests/docker/test-behat.sh tests/features/${{ matrix.feature }}.feature
