name: Test

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

jobs:

  test:
    name: Build test environment and run tests
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish DEV image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: tests/docker/DockerfileDev
          push: true
          tags: ghcr.io/trinko/giuaschool-dev:latest

      - name: Build and publish TEST image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: tests/docker/DockerfileTest
          push: true
          tags: ghcr.io/trinko/giuaschool-test:latest

      - name: Run tests
        run: |
          docker run --name "gs_test" --add-host=giuaschool_test:127.0.0.1 --add-host=chrome_headless:127.0.0.1 ghcr.io/trinko/giuaschool-test:latest tests/docker/entrypoint-test.sh
          docker cp gs_test:/var/www/giuaschool/clover.xml clover.xml

      - name: Codacy coverage reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
